### PR TITLE
Update Layer.ts

### PR DESCRIPTION
**Pull request by thejoven**
add getDescription

### CODE REVIEW

**Comment by GooGee** [comment]
Why did you add getDescription?
The `description` is just a simple text which shouldn't contain any code.

**Comment by thejoven** [comment]
> Why did you add getDescription? The `description` is just a simple text which shouldn't contain any code.

I thought this was a code comment to describe the file .
If I want to use custom comments as variables, what should I do .

**Comment by GooGee** [comment]
In script
```js
data.customComment = eval(textContainVariable)
```

In template
```
{{ customComment }}
```

**Comment by thejoven** [comment]
> In script
> 
> ```js
> data.customComment = eval(textContainVariable)
> ```
> 
> In template
> 
> ```
> {{ customComment }}
> ```

I can also use this tool to generate front-end pages inside the project, which is flexible. Thank you for your open source

**Pull request closed without merging**
